from numpy import arange, array, random, where, reshape, log10, sqrt, mean
from os import system, path
from misc_tools import listdir_extension
from obspy import Trace

def read_smc_file(acc_file):
    # reads the "smc" file (synthetic accelerogram generated by smsim)
    # outputs the displacement as obspy trace object in SI format (meters)

    f = open(acc_file, 'r')
    lines = f.readlines()[40:]
    f.close()
    
    acc = []
    for ln in lines:
        for i in range(0, int(len(ln)/10)):
            acc.append(float(ln[10*i:10*(i + 1)]))
        
    acc = array(acc)
    l = len(acc) * 8
    #acc = reshape(acc, (1, l))[0]

    acc_tr = Trace()
    acc_tr.data = acc / 100.
    acc_tr.stats.sampling_rate = 100.
    acc_tr.stats.delta = 0.01

    disp_trace = acc_tr.copy().integrate().integrate()
    
    return disp_trace

def get_wa_amp(displacement_trace):

    # claculate the displacement amplitude from Wood-Anderson seismometer

    paz_wa = {'sensitivity': 2080, 'zeros': [0j, 0j], 'gain': 1,
              'poles': [-6.2832 - 4.7124j, -6.2832 + 4.7124j]}
    disp_wa = displacement_trace.copy().simulate(paz_remove=None,
                                                 paz_simulate=paz_wa, water_level=10)

    ampl = max(abs(disp_wa.data))

    return ampl * 1000.


# run smsim
def run_smsim(m, d):
    # read base ctrl
    lines = open('allen07_a_ts_drvr_base.ctl').readlines()

    # now, write ctrl file
    lines[8] = '  simulations/m'+str('%0.2f' % m)+'r'+str('%0.1f' % d)+'_\n'
    lines[10] = '  '+str('%0.2f' % m)+' '+str('%0.1f' % d) + '\n'
    
    # write ctrl file
    f = open('allen07_a_ts_drvr.ctl', 'w')
    f.writelines(lines)
    f.close()
    
    # now call smsim
    system('./a_ts_drvr_mod')
    
################################################################################
# get event data

def get_event_data():
    from os import remove
    
    smcfiles = listdir_extension('simulations', 'smc')
    
    wa_amps = []
    for smcfile in smcfiles:
        # get mag-dist from filename
        m = smcfile[1:5]
        r = smcfile.split('r')[-1].split('_')[0]
        
        disp_trace = read_smc_file(path.join('simulations',smcfile)) # in m
        wa_amps.append(get_wa_amp(disp_trace))
        
        '''
        # add random Gaussian to WA amps                               
        rand_gaus = random.normal(loc=0., scale=0.25, size=1)
        wa_amp = 10**(log10(wa_amp) + rand_gaus[0])                     
        
        #data += ','.join((m, r, str(wa_amp))) + '\n'
        '''
        # now remove file
        remove(path.join('simulations',smcfile))
    return wa_amps
    
################################################################################
def get_bvalue(mfd_mrng, mag_list, n_yrs):
    # get cumulative rates for mags >= m
    cum_num = []
    
    # add small number to deal with precission issues
    for m in mfd_mrng:
        midx = where(mag_list+1E-7 >= m)[0]    
        # set temp cum mags & times
        cum_num.append(len(midx))
        
    # get events per mag bin
    n_obs = []
    for r in range(0, len(cum_num)-1):
        n_obs.append(cum_num[r] - cum_num[r+1])
    n_obs.append(cum_num[-1])
    n_obs = array(n_obs)
    bin_rates = array(cum_num) / n_yrs
    
    # get bval
    mc = 1.8
    b_val, sigma_b = aki_maximum_likelihood(mfd_mrng, n_obs, mc)
    #a_val = fit_a_value(cum_num, bvals, mfd_mrng, mc, m_upper)
    
    return b_val, sigma_b, cum_num, n_obs, bin_rates
    
################################################################################

import pickle
from oq_tools import get_oq_incrementalMFD
from hazard_tools import bval2beta
from catalogue_tools import aki_maximum_likelihood, fit_a_value
from calculate_magnitudes import calc_R35, calc_HB87, calc_MLM92, calc_BJ84
from misc_tools import dictlist2array, get_mpl2_colourlist
from numpy import around
from scipy.stats import norm, trim_mean
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.style.use('classic')

fig = plt.figure(1, figsize=(7,8))
cols = get_mpl2_colourlist()

# get event set
bval_start = 1.2
beta = bval2beta(bval_start)

N0 = 1
mmin = 2.1
mmax = 7.3
binwid = 0.05

# get incremental curve
betacurve, mrng = get_oq_incrementalMFD(beta, N0, mmin, mmax, binwid)
idx5 = 65 # M 5 index

# sum rates M >= 5
m5_plus_rate = sum(betacurve[idx5:])

# get M 5 rate of 1 per 20 yrs
n_yrs = 20
target_m5_rate = 1 / n_yrs

# normalise betacurve by M 5 rate
target_curve = target_m5_rate * betacurve / m5_plus_rate

# sample beta curve
prob_curve = target_curve / sum(target_curve)

# smaple events
print('Check Mag Sample!!!!!!')
mag_sample = random.choice(mrng, size=800, p=prob_curve, replace=True) 

mfd_mrng = arange(2.15, 7.4, 0.1)
b_val, sigma_b, cum_num, n_obs, bin_rates = get_bvalue(mfd_mrng, mag_sample, n_yrs)

pidx = n_obs > 0
plt.semilogy(mfd_mrng[pidx], bin_rates[pidx], 'o', c=cols[0], label='MW (b = '+str('%0.2f' % b_val)+')')

# get num stations for given mag
def get_nstas(mag):
    import pickle
    numPDF = pickle.load(open("../numPDF.pkl", "rb" ))
    
    for npdf in numPDF: 
        if npdf['mmin'] >= mag and npdf['mmax'] < mag:
            nstas = around(norm.rvs(npdf['mu'], npdf['std'], size=1))

    return nstas
    
# get get distances for given mag and nstas
def get_distances(mag, nstas):
    import pickle
    distPDF = pickle.load(open("../distPDF.pkl", "rb" ))
    
    for dpdf in distPDF: 
        if dpdf['mmin'] >= mag and dpdf['mmax'] < mag:
            try:
                sample_dists = 10**(norm.rvs(dpdf['mu'], dpdf['std'], size=int(nstas)))
            except: #try again!
                try:
                    sample_dists = 10**(norm.rvs(dpdf['mu'], dpdf['std'], size=int(nstas)))
                except: #try again!
                    sample_dists = array([0])

    return sample_dists


# do smsim magic - only continue if within reasonable range!
events = []
if b_val > 1.17 and b_val < 1.23:

    # loop thru mag sample
    for mag in mag_sample:
        # get sample number of stations
        nstas = get_nstas(mag)
        
        # get sample distances
        sample_dists = get_distances(mag, nstas)
        
        idx = sample_dists > 800.
        sample_dists = delete(sample_dists, idx)
        idx = sample_dists < 10.
        sample_dists = delete(sample_dists, idx)
        
        # run smsim
        if len(sample_dists) > 0:
            for dist in sample_dists:
                run_smsim(mag, dist)
                
            # get event data
            wa_amps = get_event_data()
            
            events.append({'mw':mag, 'wa_amps':wa_amps, 'dists':sample_dists})

################################################################################
# calculate mags
for j, event in enumerate(events):
    bj84 = []
    mlm92 = []
    for i in range(0, len(event['wa_amps'])):
        if event['dists'][i] < 10.:
            event['dists'][i] == 10
        
        repi = sqrt(event['dists'][i]**2 - 10**2)
        
        bj84.append(calc_BJ84(1, log10(event['wa_amps'][i]), event['dists'][i]) + 0.18) # added 0.18 as mean H-V correction - see hv_ratio.png in dropbox
        mlm92.append(calc_MLM92(0, log10(event['wa_amps'][i]), event['dists'][i]))
    
    events[j]['bj84'] = bj84
    events[j]['bj84_mean'] = trim_mean(bj84, 0.1)
    
    events[j]['mlm92'] = mlm92
    events[j]['mlm92_mean'] = trim_mean(mlm92, 0.1)

# get arrays for b-value
bj84_array = dictlist2array(events, 'bj84_mean')
mlm92_array = dictlist2array(events, 'mlm92_mean') 

# get b-values and plot
b_val_bj84, sigma_b, cum_num, n_obs, bin_rates = get_bvalue(mfd_mrng, bj84_array, n_yrs)

pidx = n_obs > 0
plt.semilogy(mfd_mrng[pidx], bin_rates[pidx], 'o', c=cols[1], label='ML BL84 (b = '+str('%0.2f' % b_val_bj84)+')')

b_val_mlm92, sigma_b, cum_num, n_obs, bin_rates = get_bvalue(mfd_mrng, mlm92_array, n_yrs)

pidx = n_obs > 0
plt.semilogy(mfd_mrng[pidx], bin_rates[pidx], 'o', c=cols[2], label='ML MLM92 (b = '+str('%0.2f' % b_val_mlm92)+')')


################################################################################
# plot mfd


plt.xlabel('Magnitude', fontsize=16)
plt.ylabel('Annual Rate (/yr)', fontsize=16)
plt.grid(which='both')
plt.legend(loc=1, numpoints=3)
plt.xlim([1.75, 5.25])

plt.savefig('mag_b_value_comp.png',format='png', dpi=300, bbox_inches='tight')
plt.show()

'''
mx = 1.8
# get n stasions
        
# now get distances for Nstas

        
print(sample_dists)
'''
print('\n')
