period         = PGA
outfile        = neodom_vs_smoothed_bval_regional
relativepaths  = jobs/neodom_b_var_mc/results/neodom_hazard_curve-mean-PGA_28.csv;jobs/smoothed_b_var_mc/results/gridded_hazard_curve-mean-PGA_31.csv
hazcurvelabels = NSHA23 b-value;Smoothed b-value
outputdir      = hazard_curves
sitelistfile   = jobs/nsha_cities.csv
pltplaces      = Kalgoorlie;Broome;Morwell;Townsville;Bundaberg;Newcastle