period         = PGA
outfile        = neodom_vs_smoothed_bval
relativepaths  = jobs/neodom_b_var_mc/results/neodom_hazard_curve-mean-PGA_28.csv;jobs/smoothed_b_var_mc/results/gridded_hazard_curve-mean-PGA_31.csv
hazcurvelabels = Domains b-value;Smoothed b-value
outputdir      = hazard_curves
sitelistfile   = jobs/nsha_cities.csv
pltplaces      = Adelaide;Brisbane;Canberra;Melbourne;Perth;Sydney